### ISSUE TITLE
About the evaluation on Europarl

### ISSUE THREAD

**Issue by Mao-KU** [rlitschk/EncoderCLIR#1]
Hi, 

Glad to see this insightful evaluation paper for multilingual encoders.
I saw that you conducted the evaluation using the Europarl dataset for LASER, LaBSE, etc.
Are there any data leak issues for those evaluations because Europarl are already used as the training data for LASER, LaBSE, etc.

Thank you in advance.

Mao

**Comment by rlitschk** [comment]
Hi Mao,

Yes you are right about the data leak issues, we also mention this in the paper:

"This however, does not come as much of a surprise, since these models (a) have been trained using
parallel data, and (b) have been optimized exactly on the sentence similarity task. In
other words, in the context of the cross-lingual sentence-level task, these models are
effectively supervised models. The effect of supervision is most strongly pronounced for
LASER, which was, by being also trained on parallel data from Europarl, effectively
subdued to in-domain training."

Best,
Robert
